services:
  miniflux:
    environment:
      ADMIN_PASSWORD_FILE: /run/secrets/miniflux_admin_password
      ADMIN_USERNAME_FILE: /run/secrets/miniflux_admin_username
      CREATE_ADMIN: "1"
    secrets:
      - miniflux_admin_password
      - miniflux_admin_username

secrets:
  miniflux_admin_password:
    file: ./.miniflux-secrets/runtime/admin_password
  miniflux_admin_username:
    file: ./.miniflux-secrets/runtime/admin_username
