import type { SupabaseClient } from '@supabase/supabase-js'
import type { QACitation } from '@/lib/diligence/qa-answer'
import type { Database, Json } from '@/lib/types/database'

export interface PromoteDiligenceChatEvidenceParams {
  admin: SupabaseClient<Database>
  fundId: string
  dealId: string
  userId: string
  question: string
  answer: string
  citations: readonly QACitation[]
  stableId: string
  conversationId: string
  model: string
  answeredAt?: string
}

export interface ReplaceDiligenceSessionQAAnswersParams {
  admin: SupabaseClient<Database>
  fundId: string
  dealId: string
  draftId: string
  sessionRecords: readonly QARecord[]
}

export type PromoteDiligenceChatEvidenceResult = 'promoted' | 'duplicate' | 'no-draft' | 'limit' | 'failed'

type QARecord = Record<string, unknown> & { question_id?: unknown }

function qaRecord(value: unknown): value is QARecord {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

/**
 * Replace answers generated by the current agent session while retaining every externally authored
 * record (partner questions, project-chat evidence, and future sources unknown to this stage).
 */
export function mergeSessionAndExternalQAAnswers(
  sessionRecords: readonly QARecord[],
  existingValue: unknown,
): QARecord[] {
  const sessionIds = new Set(sessionRecords.flatMap(record => (
    typeof record.question_id === 'string' ? [record.question_id] : []
  )))
  const external = Array.isArray(existingValue)
    ? existingValue.filter(qaRecord).filter(record => (
      typeof record.question_id === 'string' && !sessionIds.has(record.question_id)
    ))
    : []
  return [...sessionRecords.map(record => ({ ...record })), ...external.map(record => ({ ...record }))]
}

/**
 * Replace the records owned by one memo-agent QA session under the same row lock used by chat
 * promotion. This prevents a stage completion from overwriting an answer promoted concurrently.
 */
export async function replaceDiligenceSessionQAAnswers({
  admin,
  fundId,
  dealId,
  draftId,
  sessionRecords,
}: ReplaceDiligenceSessionQAAnswersParams): Promise<QARecord[]> {
  const sessionIds = sessionRecords.flatMap(record => (
    typeof record.question_id === 'string' ? [record.question_id] : []
  ))
  const { data, error } = await admin.rpc('replace_diligence_session_qa_answers', {
    p_fund_id: fundId,
    p_deal_id: dealId,
    p_draft_id: draftId,
    p_session_ids: sessionIds,
    p_session_records: sessionRecords.map(record => ({ ...record })) as Json,
  })
  if (error || !Array.isArray(data)) {
    throw new Error('Could not atomically persist diligence QA answers')
  }
  const rows: unknown[] = data
  return rows.filter(qaRecord).map(record => ({ ...record }))
}

/** Atomic, bounded, best-effort promotion into the latest live memo draft. */
export async function promoteDiligenceChatEvidence({
  admin,
  fundId,
  dealId,
  userId,
  question,
  answer,
  citations,
  stableId,
  conversationId,
  model,
  answeredAt = new Date().toISOString(),
}: PromoteDiligenceChatEvidenceParams): Promise<PromoteDiligenceChatEvidenceResult> {
  const entry = {
    question_id: stableId,
    question_text: question,
    answer_text: answer,
    partner_id: null,
    requested_by: userId,
    answered_at: answeredAt,
    generated_at: answeredAt,
    feeds_dimensions: [],
    category: 'chat_qa',
    source: 'analyst_project_chat',
    source_kind: 'assistant_derived',
    evidence_class: 'derived_answer',
    verification_status: 'unverified',
    excluded: true,
    conversation_id: conversationId,
    model,
    citations: [...citations],
  }
  try {
    const { data, error } = await admin.rpc('append_diligence_qa_answer', {
      p_fund_id: fundId,
      p_deal_id: dealId,
      p_stable_id: stableId,
      p_entry: entry as unknown as Json,
    })
    if (error) return 'failed'
    return data === 'promoted' || data === 'duplicate' || data === 'no-draft' || data === 'limit'
      ? data
      : 'failed'
  } catch {
    return 'failed'
  }
}
