ALTER TABLE public.diligence_agent_sessions
  ADD COLUMN IF NOT EXISTS draft_id uuid REFERENCES public.diligence_memo_drafts(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS diligence_agent_sessions_draft_idx
  ON public.diligence_agent_sessions(fund_id, deal_id, draft_id, updated_at DESC);

DROP FUNCTION IF EXISTS append_diligence_partner_answers(uuid, uuid, uuid, uuid, jsonb);

CREATE OR REPLACE FUNCTION append_diligence_partner_answers(
  p_fund_id uuid,
  p_deal_id uuid,
  p_session_id uuid,
  p_draft_id uuid,
  p_partner_id uuid,
  p_answers jsonb
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  current_messages jsonb;
  enriched_answers jsonb;
  next_messages jsonb;
  authoritative_draft_id uuid;
BEGIN
  IF jsonb_typeof(p_answers) IS DISTINCT FROM 'array'
    OR jsonb_array_length(p_answers) = 0
    OR jsonb_array_length(p_answers) > 100
    OR octet_length(p_answers::text) > 1900000
    OR EXISTS (
      SELECT 1 FROM jsonb_array_elements(p_answers) AS item
      WHERE jsonb_typeof(item) IS DISTINCT FROM 'object'
        OR jsonb_typeof(item -> 'question_id') IS DISTINCT FROM 'string'
        OR length(item ->> 'question_id') = 0
        OR length(item ->> 'question_id') > 256
        OR jsonb_typeof(item -> 'answer_text') IS DISTINCT FROM 'string'
        OR length(item ->> 'answer_text') = 0
        OR octet_length(item ->> 'answer_text') > 100000
    ) THEN
    RETURN 'limit';
  END IF;

  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(p_deal_id::text, 0)
  );
  PERFORM id
  FROM public.diligence_deals
  WHERE id = p_deal_id
    AND fund_id = p_fund_id
  FOR UPDATE;
  IF NOT FOUND THEN
    RETURN 'not-found';
  END IF;
  SELECT id
    INTO authoritative_draft_id
  FROM public.diligence_memo_drafts
  WHERE fund_id = p_fund_id
    AND deal_id = p_deal_id
    AND is_draft = true
  ORDER BY created_at DESC, id DESC
  LIMIT 1;
  IF authoritative_draft_id IS DISTINCT FROM p_draft_id THEN
    RETURN 'stale-draft';
  END IF;

  SELECT messages
    INTO current_messages
  FROM public.diligence_agent_sessions
  WHERE id = p_session_id
    AND fund_id = p_fund_id
    AND deal_id = p_deal_id
    AND draft_id = p_draft_id
    AND stage = 'qa'
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN 'not-found';
  END IF;
  IF jsonb_typeof(current_messages) IS DISTINCT FROM 'array' THEN
    RETURN 'invalid-session';
  END IF;

  SELECT jsonb_agg(item || jsonb_build_object('partner_id', p_partner_id))
    INTO enriched_answers
  FROM jsonb_array_elements(p_answers) AS item;

  next_messages := current_messages || jsonb_build_array(jsonb_build_object(
    'role', 'partner_answer',
    'ts', to_char(clock_timestamp() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'),
    'data', jsonb_build_object('answers', enriched_answers)
  ));

  IF jsonb_array_length(next_messages) > 1000
    OR octet_length(next_messages::text) > 4194304
    OR (
      SELECT count(DISTINCT answer ->> 'question_id')
      FROM jsonb_array_elements(next_messages) AS message
      CROSS JOIN LATERAL jsonb_array_elements(
        CASE
          WHEN jsonb_typeof(message #> '{data,answers}') = 'array'
            THEN message #> '{data,answers}'
          ELSE '[]'::jsonb
        END
      ) AS answer
      WHERE message ->> 'role' = 'partner_answer'
    ) > 200 THEN
    RETURN 'limit';
  END IF;

  UPDATE public.diligence_agent_sessions
  SET messages = next_messages,
      updated_at = now()
  WHERE id = p_session_id
    AND fund_id = p_fund_id
    AND deal_id = p_deal_id
    AND draft_id = p_draft_id
    AND stage = 'qa';

  IF NOT FOUND THEN
    RETURN 'not-found';
  END IF;
  RETURN 'recorded';
END;
$$;

REVOKE ALL ON FUNCTION append_diligence_partner_answers(uuid, uuid, uuid, uuid, uuid, jsonb)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION append_diligence_partner_answers(uuid, uuid, uuid, uuid, uuid, jsonb)
  TO service_role;

-- Append only the messages generated by one AI batch. The row lock makes this compose with
-- partner answers instead of replacing a stale messages snapshot after a long model call.
DROP FUNCTION IF EXISTS append_diligence_qa_session_messages(uuid, uuid, uuid, jsonb);
DROP FUNCTION IF EXISTS append_diligence_qa_session_messages(uuid, uuid, uuid, integer, jsonb);

CREATE OR REPLACE FUNCTION append_diligence_qa_session_messages(
  p_fund_id uuid,
  p_deal_id uuid,
  p_session_id uuid,
  p_draft_id uuid,
  p_expected_message_count integer,
  p_messages jsonb
)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  current_messages jsonb;
  next_messages jsonb;
  authoritative_draft_id uuid;
BEGIN
  IF p_expected_message_count IS NULL
    OR p_expected_message_count < 0
    OR p_expected_message_count > 1000
    OR jsonb_typeof(p_messages) IS DISTINCT FROM 'array'
    OR jsonb_array_length(p_messages) = 0
    OR jsonb_array_length(p_messages) > 2
    OR octet_length(p_messages::text) > 1048576
    OR EXISTS (
      SELECT 1 FROM jsonb_array_elements(p_messages) AS item
      WHERE jsonb_typeof(item) IS DISTINCT FROM 'object'
        OR item ->> 'role' NOT IN ('agent_batch', 'agent_covered')
        OR jsonb_typeof(item -> 'ts') IS DISTINCT FROM 'string'
        OR length(item ->> 'ts') > 64
        OR jsonb_typeof(item -> 'data') IS DISTINCT FROM 'object'
    ) THEN
    RETURN 'limit';
  END IF;

  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(p_deal_id::text, 0)
  );
  PERFORM id
  FROM public.diligence_deals
  WHERE id = p_deal_id
    AND fund_id = p_fund_id
  FOR UPDATE;
  IF NOT FOUND THEN
    RETURN 'not-found';
  END IF;
  SELECT id
    INTO authoritative_draft_id
  FROM public.diligence_memo_drafts
  WHERE fund_id = p_fund_id
    AND deal_id = p_deal_id
    AND is_draft = true
  ORDER BY created_at DESC, id DESC
  LIMIT 1;
  IF authoritative_draft_id IS DISTINCT FROM p_draft_id THEN
    RETURN 'stale-draft';
  END IF;

  SELECT messages
    INTO current_messages
  FROM public.diligence_agent_sessions
  WHERE id = p_session_id
    AND fund_id = p_fund_id
    AND deal_id = p_deal_id
    AND draft_id = p_draft_id
    AND stage = 'qa'
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN 'not-found';
  END IF;
  IF jsonb_typeof(current_messages) IS DISTINCT FROM 'array' THEN
    RETURN 'invalid-session';
  END IF;
  IF jsonb_array_length(current_messages) <> p_expected_message_count THEN
    RETURN 'conflict';
  END IF;

  next_messages := current_messages || p_messages;
  IF jsonb_array_length(next_messages) > 1000 OR octet_length(next_messages::text) > 4194304 THEN
    RETURN 'limit';
  END IF;

  UPDATE public.diligence_agent_sessions
  SET messages = next_messages,
      updated_at = now()
  WHERE id = p_session_id
    AND fund_id = p_fund_id
    AND deal_id = p_deal_id
    AND draft_id = p_draft_id
    AND stage = 'qa';

  IF NOT FOUND THEN
    RETURN 'not-found';
  END IF;
  RETURN 'appended';
END;
$$;

REVOKE ALL ON FUNCTION append_diligence_qa_session_messages(uuid, uuid, uuid, uuid, integer, jsonb)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION append_diligence_qa_session_messages(uuid, uuid, uuid, uuid, integer, jsonb)
  TO service_role;

-- Serialize the check-then-create path even when no session row exists yet. This keeps all
-- callers on one open QA session without rewriting historical duplicate sessions.
CREATE OR REPLACE FUNCTION start_diligence_qa_session(
  p_fund_id uuid,
  p_deal_id uuid,
  p_draft_id uuid,
  p_user_id uuid
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  target_session_id uuid;
  authoritative_draft_id uuid;
BEGIN
  IF p_user_id IS NULL THEN
    RETURN NULL;
  END IF;

  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(p_deal_id::text, 0)
  );

  PERFORM id
  FROM public.diligence_deals
  WHERE id = p_deal_id
    AND fund_id = p_fund_id
  FOR UPDATE;
  IF NOT FOUND THEN
    RETURN NULL;
  END IF;

  SELECT id
    INTO authoritative_draft_id
  FROM public.diligence_memo_drafts
  WHERE fund_id = p_fund_id
    AND deal_id = p_deal_id
    AND is_draft = true
  ORDER BY created_at DESC, id DESC
  LIMIT 1;
  IF authoritative_draft_id IS DISTINCT FROM p_draft_id THEN
    RETURN NULL;
  END IF;

  PERFORM id
  FROM public.diligence_memo_drafts
  WHERE id = p_draft_id
    AND fund_id = p_fund_id
    AND deal_id = p_deal_id
    AND is_draft = true
  FOR KEY SHARE;
  IF NOT FOUND THEN
    RETURN NULL;
  END IF;

  SELECT id
    INTO target_session_id
  FROM public.diligence_agent_sessions
  WHERE fund_id = p_fund_id
    AND deal_id = p_deal_id
    AND draft_id = p_draft_id
    AND stage = 'qa'
  ORDER BY updated_at DESC, id DESC
  LIMIT 1;

  IF target_session_id IS NULL THEN
    INSERT INTO public.diligence_agent_sessions(
      deal_id,
      fund_id,
      draft_id,
      stage,
      title,
      messages,
      created_by
    ) VALUES (
      p_deal_id,
      p_fund_id,
      p_draft_id,
      'qa',
      'Stage 3 Q&A',
      '[]'::jsonb,
      p_user_id
    )
    RETURNING id INTO target_session_id;
  END IF;

  UPDATE public.diligence_deals
  SET current_memo_stage = 'qa'
  WHERE id = p_deal_id
    AND fund_id = p_fund_id;

  RETURN target_session_id;
END;
$$;

REVOKE ALL ON FUNCTION start_diligence_qa_session(uuid, uuid, uuid, uuid)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION start_diligence_qa_session(uuid, uuid, uuid, uuid)
  TO service_role;

-- Close the QA session and persist its latest partner answers in one transaction. The session
-- lock serializes completion with both partner and AI appends, so an accepted answer cannot be
-- omitted while the project advances to the draft stage.
CREATE OR REPLACE FUNCTION finish_diligence_qa_session(
  p_fund_id uuid,
  p_deal_id uuid,
  p_session_id uuid,
  p_draft_id uuid,
  p_question_metadata jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  current_messages jsonb;
  current_stage text;
  current_answers jsonb;
  message_item jsonb;
  answer_item jsonb;
  question_id text;
  metadata_item jsonb;
  answer_map jsonb := '{}'::jsonb;
  session_records jsonb;
  session_ids text[];
  merged_answers jsonb;
  authoritative_draft_id uuid;
BEGIN
  IF jsonb_typeof(p_question_metadata) IS DISTINCT FROM 'object'
    OR octet_length(p_question_metadata::text) > 1048576
    OR (SELECT count(*) FROM jsonb_each(p_question_metadata)) > 1000
    OR EXISTS (
      SELECT 1 FROM jsonb_each(p_question_metadata) AS metadata(key, value)
      WHERE length(metadata.key) = 0
        OR length(metadata.key) > 256
        OR jsonb_typeof(metadata.value) IS DISTINCT FROM 'object'
    ) THEN
    RAISE EXCEPTION 'invalid QA question metadata';
  END IF;

  -- Share the deal-scoped transaction lock with draft-version creation. This prevents an old
  -- tab from completing after a newer authoritative draft appears during this transaction.
  PERFORM pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(p_deal_id::text, 0)
  );

  PERFORM id
  FROM public.diligence_deals
  WHERE id = p_deal_id
    AND fund_id = p_fund_id
  FOR UPDATE;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('status', 'not-found');
  END IF;

  SELECT id
    INTO authoritative_draft_id
  FROM public.diligence_memo_drafts
  WHERE fund_id = p_fund_id
    AND deal_id = p_deal_id
    AND is_draft = true
  ORDER BY created_at DESC, id DESC
  LIMIT 1;

  IF authoritative_draft_id IS DISTINCT FROM p_draft_id THEN
    RETURN jsonb_build_object('status', 'stale-draft');
  END IF;

  SELECT messages, stage
    INTO current_messages, current_stage
  FROM public.diligence_agent_sessions
  WHERE id = p_session_id
    AND fund_id = p_fund_id
    AND deal_id = p_deal_id
    AND draft_id = p_draft_id
    AND stage IN ('qa', 'qa_complete')
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('status', 'not-found');
  END IF;

  IF current_stage = 'qa_complete' THEN
    SELECT qa_answers
      INTO current_answers
    FROM public.diligence_memo_drafts
    WHERE id = p_draft_id
      AND fund_id = p_fund_id
      AND deal_id = p_deal_id
      AND is_draft = true;
    IF current_answers IS NULL THEN
      RETURN jsonb_build_object('status', 'not-found');
    END IF;
    RETURN jsonb_build_object('status', 'completed', 'answers', current_answers);
  END IF;

  IF jsonb_typeof(current_messages) IS DISTINCT FROM 'array' THEN
    RAISE EXCEPTION 'invalid QA session messages';
  END IF;

  FOR message_item IN SELECT value FROM jsonb_array_elements(current_messages)
  LOOP
    IF message_item ->> 'role' = 'partner_answer'
      AND jsonb_typeof(message_item #> '{data,answers}') = 'array' THEN
      FOR answer_item IN SELECT value FROM jsonb_array_elements(message_item #> '{data,answers}')
      LOOP
        question_id := answer_item ->> 'question_id';
        IF question_id IS NOT NULL
          AND length(question_id) BETWEEN 1 AND 256
          AND jsonb_typeof(answer_item -> 'answer_text') = 'string'
          AND octet_length(answer_item ->> 'answer_text') <= 100000 THEN
          metadata_item := coalesce(p_question_metadata -> question_id, '{}'::jsonb);
          answer_map := jsonb_set(
            answer_map,
            ARRAY[question_id],
            jsonb_build_object(
              'answer_text', answer_item ->> 'answer_text',
              'partner_id', answer_item -> 'partner_id',
              'answered_at', message_item ->> 'ts',
              'feeds_dimensions', coalesce(metadata_item -> 'feeds_dimensions', '[]'::jsonb),
              'category', metadata_item -> 'category'
            ),
            true
          );
        END IF;
      END LOOP;
    END IF;
  END LOOP;

  SELECT coalesce(jsonb_agg(record || jsonb_build_object('question_id', id) ORDER BY id), '[]'::jsonb),
         coalesce(array_agg(id ORDER BY id), ARRAY[]::text[])
    INTO session_records, session_ids
  FROM jsonb_each(answer_map) AS answers(id, record);

  merged_answers := public.replace_diligence_session_qa_answers(
    p_fund_id,
    p_deal_id,
    p_draft_id,
    session_ids,
    session_records
  );

  UPDATE public.diligence_agent_sessions
  SET stage = 'qa_complete',
      updated_at = now()
  WHERE id = p_session_id
    AND fund_id = p_fund_id
    AND deal_id = p_deal_id
    AND draft_id = p_draft_id
    AND stage = 'qa';
  IF NOT FOUND THEN
    RAISE EXCEPTION 'QA session changed while finishing';
  END IF;

  UPDATE public.diligence_deals
  SET current_memo_stage = 'draft'
  WHERE id = p_deal_id
    AND fund_id = p_fund_id
    AND current_memo_stage = 'qa';

  RETURN jsonb_build_object('status', 'completed', 'answers', merged_answers);
END;
$$;

REVOKE ALL ON FUNCTION finish_diligence_qa_session(uuid, uuid, uuid, uuid, jsonb)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION finish_diligence_qa_session(uuid, uuid, uuid, uuid, jsonb)
  TO service_role;
